#!/bin/bash
source "$(dirname "$0")/../../bin/environments.sh"
image_dir="$(dirname "$(realpath -L "$0")")"
image_name="$(basename "${image_dir}")"
image_prefix="docker.pkg.github.com/tzik/tc"

opts=(
  --rm
  -u "$(id -u):$(id -g)"
  -v "${base_dir}:${base_dir}"
  -w "${work_dir}"
)

for i in "${passing_environments[@]}"; do
  opts+=(-e "$i")
done

exec docker run "${opts[@]}" "${image_prefix}/${image_name}" "$@"
