name: bump

on:
  workflow_dispatch:
    branches: [master]
  schedule:
    - cron: '* * * * 6'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name tzik
          git config user.email mail@tzik.jp
          echo "${{secrets.VERSION_BUMP_TOKEN}}" | gh auth login --with-token
          ./bin/bump
