name: bump

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bump
        id: bump
        run: |
          git switch -c "bot/bump"
          ./bin/bump
          git config user.name 'bumpbot'
          git config user.email 'mail+bot@tzik.jp'
          git commit -am "Weekly version bump"
          git push -f origin "bot/bump"
          echo "${{secrets.GITHUB_TOKEN}}" | gh auth login --with-token
          [ "$(gh pr list --label "bot/bump" | wc -l)" -ne 0 ] || gh pr create --fill --label "bot/bump"
          pr="$(gh pr list --limit 1 --label "bot/bump" | cut -f1 -d$'\t')"
          echo "::set-output name=pr::${pr}"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{secrets.VERSION_BUMP_TOKEN}}
          labels: ci/try-requested
          number: ${{steps.bump.outputs.pr}}
