name: ci

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci_llvm:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.event_name}}"
