name: ci

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [labeled]

jobs:
  label_check:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'ci/try-requested')}}
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ci/try-requested')}}
        with:
          github_token: ${{secrets.github_token}}
          labels: ci/try-requested
  ci_llvm:
    runs-on: ubuntu-latest
    needs: label_check
    if: ${{needs.label_check.outputs.skip == 'false'}}
    strategy:
      matrix:
        distrib: [gentoo, ubuntu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: pkg/llvm/cache
          key: cache_llvm_${{matrix.distrib}}-${{github.sha}}
          restore-keys: cache_llvm_${{matrix.distrib}}-
      - name: build
        run: |
          docker login docker.pkg.github.com -u tzik -p "${{secrets.CONTAINER_REGISTRY_TOKEN}}"
          docker pull "docker.pkg.github.com/tzik/tc/builder_${{matrix.distrib}}"
          ./bin/ci ${{matrix.distrib}} llvm
      - uses: actions/upload-artifact@v2
        with:
          name: llvm_${{matrix.distrib}}
          path: pkg/llvm/llvm.tar.xz
          retention-days: 1

  ci_circt:
    runs-on: ubuntu-latest
    needs: [label_check, ci_llvm]
    if: ${{needs.label_check.outputs.skip == 'false'}}
    strategy:
      matrix:
        distrib: [gentoo, ubuntu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: pkg/circt/cache
          key: cache_circt_${{matrix.distrib}}-${{github.sha}}
          restore-keys: cache_circt_${{matrix.distrib}}-
      - uses: actions/download-artifact@v2
        with:
          name: llvm_${{matrix.distrib}}
          path: pkg/llvm
      - run: |
          unxz pkg/llvm/llvm.tar.xz
          pkg/llvm/bin/merge
      - name: build
        run: |
          docker login docker.pkg.github.com -u tzik -p "${{secrets.CONTAINER_REGISTRY_TOKEN}}"
          docker pull "docker.pkg.github.com/tzik/tc/builder_${{matrix.distrib}}"
          ./bin/ci ${{matrix.distrib}} circt
      - uses: actions/upload-artifact@v2
        with:
          name: circt_${{matrix.distrib}}
          path: pkg/circt/circt.tar.xz
          retention-days: 1

  ci_onnx:
    runs-on: ubuntu-latest
    needs: label_check
    if: ${{needs.label_check.outputs.skip == 'false'}}
    strategy:
      matrix:
        distrib: [gentoo, ubuntu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: pkg/onnx/cache
          key: cache_onnx_${{matrix.distrib}}-${{github.sha}}
          restore-keys: cache_onnx_${{matrix.distrib}}-
      - name: build
        run: |
          docker login docker.pkg.github.com -u tzik -p "${{secrets.CONTAINER_REGISTRY_TOKEN}}"
          docker pull "docker.pkg.github.com/tzik/tc/builder_${{matrix.distrib}}"
          ./bin/ci ${{matrix.distrib}} onnx
      - uses: actions/upload-artifact@v2
        with:
          name: onnx_${{matrix.distrib}}
          path: pkg/onnx/onnx.tar.xz
          retention-days: 1

  ci_pytorch:
    runs-on: ubuntu-latest
    needs: [label_check, ci_onnx]
    if: ${{needs.label_check.outputs.skip == 'false'}}
    strategy:
      matrix:
        distrib: [gentoo, ubuntu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: pkg/pytorch/cache
          key: cache_pytorch_${{matrix.distrib}}-${{github.sha}}
          restore-keys: cache_pytorch_${{matrix.distrib}}-
      - uses: actions/download-artifact@v2
        with:
          name: onnx_${{matrix.distrib}}
          path: pkg/onnx
      - run: |
          unxz pkg/onnx/onnx.tar.xz
          pkg/onnx/bin/merge
      - name: build
        run: |
          docker login docker.pkg.github.com -u tzik -p "${{secrets.CONTAINER_REGISTRY_TOKEN}}"
          docker pull "docker.pkg.github.com/tzik/tc/builder_${{matrix.distrib}}"
          ./bin/ci ${{matrix.distrib}} pytorch
      - uses: actions/upload-artifact@v2
        with:
          name: pytorch_${{matrix.distrib}}
          path: pkg/pytorch/pytorch.tar.xz
          retention-days: 1
